"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RainbowKitProvider, lightTheme } from "@rainbow-me/rainbowkit";
import { Chains, wagmiClient } from "@/wallet-config";
import { WagmiConfig } from "wagmi";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-gray-100">
      <WagmiConfig config={wagmiClient}>
        <body className="bg-gray-100">{children}</body>
      </WagmiConfig>
    </html>
  );
}
